In [1]:
import numpy as np

In [3]:
U = np.matrix([[1,0,0,0],[0,0.6,-0.8,0],[0,0.8,0.6,0],[0,0,0,1]])
S = np.matrix([[6,0,0],[0,4,0],[0,0,2],[0,0,0]])
V = np.matrix([[1/np.sqrt(2),1/np.sqrt(2),0],[0,0,1],[1/np.sqrt(2),-1/np.sqrt(2),0]]).T

A = U*S*V.T

In [4]:
A

matrix([[ 4.24264069,  4.24264069,  0.        ],
        [-1.13137085,  1.13137085,  2.4       ],
        [ 0.84852814, -0.84852814,  3.2       ],
        [ 0.        ,  0.        ,  0.        ]])

In [8]:
a

matrix([[4.24264069, 4.24264069, 0.        ],
        [0.        , 0.        , 2.4       ],
        [0.        , 0.        , 3.2       ],
        [0.        , 0.        , 0.        ]])

In [9]:
np.linalg.norm(a,2)

6.0

In [7]:
u = np.matrix([[1,0,0,0],[0,0.6,0.8,0]]).T
s = np.matrix([[6,0],[0,4]])
v = np.matrix([[1/np.sqrt(2),1/np.sqrt(2),0],[0,0,1]]).T

a = u*s*v.T

In [10]:
### Problem 2

In [12]:
cov = np.matrix([[2,1],[1,1]])
cov_inv = np.linalg.inv(cov)
cov_inv

matrix([[ 1., -1.],
        [-1.,  2.]])